---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "vaultwarden.fullname" . }}
  labels:
{{ include "vaultwarden.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
      protocol: TCP
      name: http
    {{- if .Values.bitwarden.websocket_enabled }}
    - port: {{ .Values.bitwarden.websocket_port }}
      targetPort: {{ .Values.bitwarden.websocket_port }}
      protocol: TCP
      name: ws
    {{- end }}
  selector:
    app: {{ template "vaultwarden.fullname" . }}