apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "adguard.fullname" . }}-config
  labels:
{{ include "adguard.labels" . | indent 4 }}
data: 
  AdGuardHome.yaml: {{ .Values.config | quote }}
