---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "twitch-miner.fullname" . }}
  labels:
{{ include "twitch-miner.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $name, $options:= .Values.service.ports }}
    - port: {{ $options.port }}
      targetPort: {{ $options.target_port }}
      protocol: {{ $options.protocol }}
      name: {{ $name }}
  {{- end }}
  selector:
    app: {{ template "twitch-miner.fullname" . }}
